# Generated by Django 4.0.3 on 2022-03-21 22:46

from django.db import migrations
from django.contrib.auth.models import User

# def create_default_auth(apps, schema_editor):
#     user = User.objects.create(
#         username='mamun',
#         email='mamun1980@gmail.com',
#         password='qweqwe123'
#     )

#     user.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        
    ]
