# Generated by Django 4.0.3 on 2022-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceURLToken',
            fields=[
                ('url_token', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
