# Generated by Django 4.0.3 on 2022-03-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceurltoken',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
