# Generated by Django 4.0.3 on 2022-03-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urltoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='urltoken',
            name='created_by',
        ),
    ]
