# Generated by Django 4.0.3 on 2022-03-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendanceurltoken_delete_urltoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceurltoken',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attendanceurltoken',
            name='status',
        ),
    ]
